### ISSUE TITLE
Adjust content overlay color

### ISSUE THREAD

**Issue by brdlyptrs** [hCaptcha/hcaptcha-android-sdk#1]
Currently there is a white opacity set on the overlay area (clickable region) behind the challenge view, see screen shot. We want to either change that to being fully transparent or black set to a 10 - 15% opacity.

![white_opacity](https://user-images.githubusercontent.com/40441278/105785757-889d2100-5f30-11eb-9c1a-4088cc5b86e1.png)

**Comment by DSergiu** [comment]
The issue of the inconsistency relies in `api.js` adding an full screen overlay with background `#FFF` and opacity `0.05`. 

Solution: overwrite the style of the 2nd inner div by setting opacity to `0`.

See PR: https://github.com/hCaptcha/hcaptcha-android-sdk/pull/2
