### ISSUE TITLE
Fix `connectedAndroidTest` UI Tests, add to CI

### ISSUE THREAD

**Issue by CAMOBAP** [hCaptcha/hcaptcha-android-sdk#11]
`./gradlew test` works correctly but `./gradlew connectedAndroidTest` fails

<img width="1317" alt="Screen Shot 2021-12-29 at 5 38 50 PM" src="https://user-images.githubusercontent.com/2169738/147691510-27dd115d-85fe-4054-a322-7658a6d85338.png">

Also, make sense to add this action to CI to run UI tests https://github.com/marketplace/actions/android-emulator-runner

**Comment by Auntiea77** [comment]
https://github.com/hCaptcha/hcaptcha-android-sdk/issues/11#issue-1090678199enableuitestandroid

**Comment by Auntiea77** [comment]
https://github.com/hCaptcha/hcaptcha-android-sdk/issues/11#issue-1090678199enableuitestandroid

**Comment by e271828-** [comment]
@CAMOBAP how are you doing on this? I see some downstream commits for it.

**Comment by CAMOBAP** [comment]
@e271828- unfortunatelly not started yet, I hope I will have some time tomorrow

**Comment by CAMOBAP** [comment]
Let me share some updates:
 - tests failing because No internet error comes from JS (7 code) isn't clear why
 - also I have been faced with an error for regular tests which can be fixed with this https://stackoverflow.com/a/23507579/902217 approach

Next steps:
 - use a similar approach like `mocj.html` for iOS, to make WebView independent on the internet
