### ISSUE TITLE
Unable to get client without fragment activity context

### ISSUE THREAD

**Issue by marius-zilinskas-tg** [hCaptcha/hcaptcha-android-sdk#112]
HCaptcha.getClient(context) casts context to FragmentActivity. If application is written with Jetpack Compose - fragment activity can not be provided.

How to get HCaptcha client when fragment activity context can not be provided?

**Comment by vladd-g** [comment]
@marius-zilinskas-tg I had the same problem and simply changed the parent to FragmentActivity, and everything seems to work ok. Did you experience any problems with this approach?

**Comment by marius-zilinskas-tg** [comment]
It does solve the problem, however, I think this should be addressed from the SDK and not the client. I would like to avoid using FragmentActivity as a parent just because of one SDK.

**Comment by CAMOBAP** [comment]
According to my vision/understanding, for Jetpack API it will be nice if SDK exposes `@Composable  fun HCaptchaDialog(...)`.

So it can be used like this

```
@Composable
fun Content(showCaptcha: Boolean) {
    ...
    if (showshowCaptcha) {
        HCaptchaDialog(onSuccess = {
           ...
        }, onFailure = {
           ...
        }) { state -> // state for 'loading', 'ready' 
            ... // custom loader can be presented here
        }
    }
    ...
}

```

@marius-zilinskas-tg @vladd-g could you please share your vision, how is the perfect integration looks for you?

**Comment by marius-zilinskas-tg** [comment]
@CAMOBAP Yes, your proposed solution looks nice

**Comment by CAMOBAP** [comment]
@gilsonjuniorpro Unfortunately SDK based on `DialogFragment` rely on `FragmentActivity` to work correctly.
We have a [dedicated issue](https://github.com/hCaptcha/hcaptcha-android-sdk/issues/127) to allow/research the possibility not to force our users to switch to FragmentActivity

**Comment by gilsonjuniorpro** [comment]
Thank you, so using any version below 3.9.0 it works with hilt without asking for the FragmentActivity

**Comment by CAMOBAP** [comment]
@gilsonjuniorpro it works **only** because you actually pass FragmentActivity or Activity that extends it.
In SDKs below 3.9.0 there is unsafe cast `(FragmentActivity) context`.

This is why we decided to make them explicit in API to avoid confusion.

**Comment by gilsonjuniorpro** [comment]
Yeah, make sense, thanks for your help

**Comment by Sophon** [comment]
Are there any updates regarding this? How does one use it in Compose without the parent being FragmentActivity?

**Comment by CAMOBAP** [comment]
@Sophon no update yet, work in progress

**Comment by CAMOBAP** [comment]
Now we support both `JetPack Compose`.

More details in https://github.com/hCaptcha/hcaptcha-android-sdk?tab=readme-ov-file#installation

Any feedback is appreciated
