### ISSUE TITLE
hCaptcha not showing challenge

### ISSUE THREAD

**Issue by Amitoj02** [hCaptcha/hcaptcha-android-sdk#14]
When I tried to implement it keep buffering and never show the challenge

- I have provided Internet permission
- I have attempted all sizes
- Using `com.github.hcaptcha:hcaptcha-android-sdk:1.1.0`
- Using `androidx.appcompat:appcompat:1.2.0`

The code I'm using is

```
final String SITE_KEY = "site key here";
final HCaptchaConfig hconfig = HCaptchaConfig.builder()
        .siteKey(SITE_KEY)
        .apiEndpoint("https://js.hcaptcha.com/1/api.js")
        .size(HCaptchaSize.NORMAL)
        .loading(true)
        .build();


HCaptcha.getClient(MainActivity.this).verifyWithHCaptcha(hconfig) 
    .addOnSuccessListener(new OnSuccessListener<HCaptchaTokenResponse>() {
        @Override
        public void onSuccess(HCaptchaTokenResponse response) {
            String userResponseToken = response.getTokenResult();
            showMessage("Success! Token: " + userResponseToken );
        }
    })
    .addOnFailureListener(new OnFailureListener() {
        @Override
        public void onFailure(HCaptchaException e) {
            showMessage("Error: " + e.getMessage() );
        }
    });
```

**Comment by CAMOBAP** [comment]
@Amitoj02 maybe you observe some errors in logcat?

**Comment by e271828-** [comment]
@Amitoj02 please try with one of the test sitekeys: https://docs.hcaptcha.com/#integration-testing-test-keys and if that works, double-check the sitekey entered.

**Comment by Amitoj02** [comment]
Alright, so I tried to compile again and it actually worked _magically_ . Maybe I missed something or it was temporary issue.
