### ISSUE TITLE
Orientation.LANDSCAPE - Sample Image not showing

### ISSUE THREAD

**Issue by daldegam** [hCaptcha/hcaptcha-android-sdk#159]
Hello, I'm experiencing strange behavior when I configure the SDK to use Orientation.LANDSCAPE.

When a captcha that requires tagging a similar image is displayed, the sample image is not displayed to the user.

Examples:

See that the sample image is not displayed
![bug1](https://github.com/hCaptcha/hcaptcha-android-sdk/assets/228961/86b7af3b-8dd7-402b-82e7-968be15052b4)
![bug2](https://github.com/hCaptcha/hcaptcha-android-sdk/assets/228961/b8f0d8de-800e-473a-b57a-4139ebd0ec56)
![bug3](https://github.com/hCaptcha/hcaptcha-android-sdk/assets/228961/42aa1db6-02e4-4e69-adea-2d54a3c7c1fa)

Example when the captcha does not need the sample image, so it is not a problem for the user:
![no-bug](https://github.com/hCaptcha/hcaptcha-android-sdk/assets/228961/bff81767-ebf2-43bb-80ca-1859c6e7ec2f)

Now when the SDK is configured for PORTRAIT, this does not happen, see:
![nobug-2](https://github.com/hCaptcha/hcaptcha-android-sdk/assets/228961/b2080e92-3304-4e09-b1af-79226c9032b5)
![nobug-1](https://github.com/hCaptcha/hcaptcha-android-sdk/assets/228961/0a8e3390-5199-41a9-9dea-8640c23071a9)

Is this a bug or am I doing something wrong?

Thanks!

**Comment by CAMOBAP** [comment]
@daldegam thanks for report, investigation in progress

**Comment by e271828-** [comment]
@daldegam this is expected, and is part of the responsive design for landscape.

**Comment by daldegam** [comment]
Sorry, but I don't understand how a user could answer a captcha like the example here:
![image](https://github.com/hCaptcha/hcaptcha-android-sdk/assets/228961/5ffd00be-fcd5-4a32-8041-f4766cfbdf91)


How will the user know what he should mark? 
In this case, Orientation.LANDSCAPE makes the use of the service unfeasible, or the user will need to press random images until they can get through. 
Or am I understanding it wrong?

Thanks

**Comment by e271828-** [comment]
@daldegam ah, I see what you're asking. This landscape mode feature is currently part of the enterprise suite, and is not officially supported without some additional sitekey configuration that avoids issues like this. We'll clarify that in the docs.

If you are an existing enterprise customer, please email support@hcaptcha.com for guidance.
