### ISSUE TITLE
Cannot use: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by androidacy-user** [hCaptcha/hcaptcha-android-sdk#166]
When calling verifyWithHCaptcha(), we get this warning and no result:

```
 W  DialogFragment.startVerification Can not perform this action after onSaveInstanceState
```

We're not sure how to resolve this.

**Comment by CAMOBAP** [comment]
HI @androidacy-user could you please share more details:
1. SDK version
2. Minimal reproducible example (code)
3. Full stack-trace
