### ISSUE TITLE
vulnerabilities in jackson databind library

### ISSUE THREAD

**Issue by hamish-snoop** [hCaptcha/hcaptcha-android-sdk#167]
Might be worth updating your 
com.fasterxml.jackson.core:jackson-databind
dependency, due to these vulnerabilities

https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-3038426
https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-3038424

**Comment by CAMOBAP** [comment]
Fixed in 4.0.3
