### ISSUE TITLE
Automate release workflow

### ISSUE THREAD

**Issue by CAMOBAP** [hCaptcha/hcaptcha-android-sdk#19]
### Proposal

On each version tag to master do:
 - `./gradlew publish`
 - create a release on Github

### Links
 - https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle
 - https://jitpack.io/docs/ANDROID/

***Update**

Looks like no `./gradlew publish` need it works a bit differently:
 - `./gradlew publishReleasePublicationToMavenLocal`
 - create GH Release, and this will trigger https://jitpack.io/ and it will do the rest

**Comment by CAMOBAP** [comment]
@e271828- correct me if I'm wrong, maybe we need some extra steps?

**Comment by e271828-** [comment]
CC @DSergiu for comments.

**Comment by DSergiu** [comment]
The release is already automated, isn't it? We chose jitpack over github packages due to popularity. 
I remember android clients had problems integrating with github packages.

**Comment by CAMOBAP** [comment]
@DSergiu thanks for the comment, I think you are right, I didn't work with jitpack releases, before. As far as I understood it listens for tags on the repo. So there is nothing to automate actually.

Closing this one
