### ISSUE TITLE
Suggestion: allow to pass siteKey

### ISSUE THREAD

**Issue by CAMOBAP** [hCaptcha/hcaptcha-android-sdk#26]
### Intro

On ios-sdk we have an option to provide `siteKey` by an entry in `Info.plist` (more info in README https://github.com/hCaptcha/hcaptcha-ios-sdk#usage)

### Proposed solution

In the Android world a similar technique is `meta-data` nodes from `AndroidManifest.xml` and many SDK use such approach, for example, Google Maps SDK https://developers.google.com/maps/documentation/android-sdk/config#step_3_add_your_api_key_to_the_project

### Open question

 - [ ] This feature has already been implemented as part of https://github.com/hCaptcha/hcaptcha-android-sdk/pull/25, should we move it to separate PR

cc @e271828- @DSergiu

**Comment by e271828-** [comment]
I think it's OK to leave it in the PR as it doesn't seem to introduce too much risk, but we do need to clearly document each scenario since people may often be using multiple sitekeys.
