### ISSUE TITLE
Support fully invisible flow

### ISSUE THREAD

**Issue by DSergiu** [hCaptcha/hcaptcha-android-sdk#37]
# What
Add support for fully invisible hCaptcha verification flow.

# ~How v1~
1. Add config option `boolean hideDialog`. 
3. In case of `hideDialog == true`:
   * the hCaptcha dialog should be completely invisible
   * the user should not be able to stop the verification process (e.g. by tapping `Back` button)

# How v2
1. Add config option `hostView` to specify the android view in which the `WebView` should be injected into. Thus allowing the client to specify a `view` he controls. By default the `hostView` should point to our `HCaptchaDialogFragment` instance.
2. The js api internal error `challenge-closed` and the error thrown when closing the android view where hCaptcha is injected must be easily distinguished. The later one can be renamed to `HCaptchaError.HOST_VIEW_CLOSED`.
   ```java
    @Override
    public void onCancel(@NonNull DialogInterface dialogInterface) {
        // User canceled the dialog through either `back` button or an outside touch
        super.onCancel(dialogInterface);
        this.onFailure(new HCaptchaException(HCaptchaError.CHALLENGE_CLOSED)); // shall be HCaptchaError.HOST_VIEW_CLOSED
    }
    ```

**Comment by CAMOBAP** [comment]
In progress

**Comment by DSergiu** [comment]
1. Adding the `WebView` to the current root view can work. A step further, would it make sense to parameterize the `view` where hCaptcha is to be injected? Example by creating a new configuration param **`HCaptchaConfig.hostView`** (or similar suggestive naming).
2. Blocking a frame from being destroyed and thus limiting the user interaction is not desirable indeed. I'll update the description above. 
  The current scenario for when the underlying view (dialog fragment) is closed, is to throw a `challenge-closed` error which is clashing with a different js api internal error `challenge-closed`. [See code](https://github.com/hCaptcha/hcaptcha-android-sdk/blob/main/sdk/src/main/java/com/hcaptcha/sdk/HCaptchaDialogFragment.java#L165-L170). Instead we can introduce a new error for when the underlying view is closed: **`HCaptchaError.HOST_VIEW_CLOSED`** (or similar suggestive naming). 
    ```java
    @Override
    public void onCancel(@NonNull DialogInterface dialogInterface) {
        // User canceled the dialog through either `back` button or an outside touch
        super.onCancel(dialogInterface);
        this.onFailure(new HCaptchaException(HCaptchaError.CHALLENGE_CLOSED)); // shall be HCaptchaError.HOST_VIEW_CLOSED
        }
    ```

**Comment by CAMOBAP** [comment]
Agree with both points

Also in the case of WebView without without a dialog we can listen for `View.OnAttachStateChangeListener` which can help implement similar functionality
