### ISSUE TITLE
core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

### ISSUE THREAD

**Issue by dayang123** [hCaptcha/hcaptcha-android-sdk#38]
Our project compileSdkVersion is  30.
After  add       implementation 'com.github.hcaptcha:hcaptcha-android-sdk:2.2.0'   and build.  The error title shows will  ocurr.
But upgrade compileSdkVersion to  31, the build will be ok. 
We can not upgrade  compileSdkVersion to 31 in a short time.   Any else can solve this?

**Comment by CAMOBAP** [comment]
@dayang123 could you please list other dependencies which are used by your application?

**Comment by e271828-** [comment]
@CAMOBAP can you add a test with the example app that targets compileSdkVersion == 30?

**Comment by CAMOBAP** [comment]
I reproduced a bit different issue, but I think the rot is the same:

```
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.appcompat:appcompat:1.4.1.
```

We need to downgrade androidx.appcompat:appcompat to 1.3 PR on the way

**Comment by e271828-** [comment]
@dayang123 Please confirm that ver 3.1.1 solves the issue for you. If not we will re-open this issue. Closing for now.
