### ISSUE TITLE
Review Sonar code smells

### ISSUE THREAD

**Issue by e271828-** [hCaptcha/hcaptcha-android-sdk#53]
- [ ] https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&id=hCaptcha_hcaptcha-android-sdk
- [ ] https://sonarcloud.io/project/security_hotspots?id=hCaptcha_hcaptcha-android-sdk#

**Comment by CAMOBAP** [comment]
Can be closed after https://github.com/hCaptcha/hcaptcha-android-sdk/pull/68 merge, because we moving to our own configs/reports
