### ISSUE TITLE
Performance analysis of invisible path

### ISSUE THREAD

**Issue by e271828-** [hCaptcha/hcaptcha-android-sdk#55]
Given the following (and most performant) scenario:

- Pre-warm assets when activity in created via HCaptcha.getClient(activity).setup(hCaptchaConfig)
- Perform verification when the user clicks a button via hCatpcha.verifyWithHCaptcha()

Setup visible captcha with the following configuration:

```
hideDialog(false)
loading(true)
siteKey(siteKey)
size(HCaptchaSize.NORMAL)
```

Setup invisible captcha with the following configuration:
```
hideDialog(true)
loading(false)
siteKey(siteKey)
size(HCaptchaSize.INVISIBLE)
```

When the app is configured for **invisible** then initialization performance drops compared to visible captcha, i.e. UI lag/freeze time increases significantly.

**Comment by DSergiu** [comment]
@CAMOBAP it is probably [this line](https://github.com/hCaptcha/hcaptcha-android-sdk/blob/main/sdk/src/main/java/com/hcaptcha/sdk/HCaptcha.java#L88) which is run on main UI thread resulting in UI freezes until the webview is initialized:

```java
captchaVerifier = new HCaptchaHeadlessWebView(activity, this.config, listener);
```

**Comment by CAMOBAP** [comment]
@DSergiu right, but unfortunatelly there is no way to construct UI components outside UI thread

https://github.com/hCaptcha/hcaptcha-android-sdk/pull/67 - @DSergiu , @e271828-  benchmark test are ready for review

**Comment by e271828-** [comment]
> @DSergiu right, but unfortunately there is no way to construct UI components outside UI thread

Can a Runnable with runOnUiThread or similar help here?

```
    runOnUiThread(new Runnable() {
        @Override
        public void run() {
           ...
        }
    });
```

**Comment by CAMOBAP** [comment]
> > @DSergiu right, but unfortunately there is no way to construct UI components outside UI thread
> 
> Can a Runnable with runOnUiThread or similar help here?
> 
> ```
>     runOnUiThread(new Runnable() {
>         @Override
>         public void run() {
>            ...
>         }
>     });
> ```

AFAIR if it called from UI thread it will call `run` method directly, because it's implementation is close to:

```
    public final void runOnUiThread(Runnable action) {
        if (Thread.currentThread() == mUiThread) {
            action.run();
        }
        ...
    }
```

**Comment by CAMOBAP** [comment]
Benchmark tests implemented
