### ISSUE TITLE
Generate IHCaptchaHtmlProvider implementation at build time 

### ISSUE THREAD

**Issue by CAMOBAP** [hCaptcha/hcaptcha-android-sdk#62]
### Intro
A nice proposal was made by @DSergiu  https://github.com/hCaptcha/hcaptcha-android-sdk/pull/61#discussion_r927418231 . Because maintaining embedded HTML it's really error-prone and not convenient

### Proposal

Put back `hcaptcha-form.html`  (but keep it outside of assets) and generate `IHCaptchaHtmlProvider` at build time

TODO Check existing code-gen plugins for gradle to keep Androd Studio happy (and not report missing classes)

**Comment by cryptoroland** [comment]
[]()

**Comment by CAMOBAP** [comment]
PR is ready for review https://github.com/hCaptcha/hcaptcha-android-sdk/pull/80
