### ISSUE TITLE
Immediate retry on challenge closed

### ISSUE THREAD

**Issue by hamish-snoop** [hCaptcha/hcaptcha-android-sdk#73]
We're attempting to auto trigger verification on challenge closed error. It seems this is causing a bit of a timing problem and the SDK thinks the dialog is still showing because I get a console log message: 
"DialogFragment was already added"
But no actual onFailure callback, leaving us in an unhandled state.

I currently have a workaround to pause a bit before triggering the auto-retry verification, which seems to work.

regards

Samsung S21 Android 12 device
SDK version 3.3.3

**Comment by CAMOBAP** [comment]
Implemented with `HCaptchaConfig.retryPredicate` check README for more information
