### ISSUE TITLE
Clear listeners

### ISSUE THREAD

**Issue by amusejfo** [hCaptcha/hcaptcha-android-sdk#99]
Hi! Not really the biggest issue, but, i'd like to be able to clear all listeners registered to the hCaptcha client whenever they are not needed anymore to optimize. Else they just lay around doing nothing when they might not be needed. There does not seem to be a way to this right now?

**Comment by CAMOBAP** [comment]
@amusejfo thanks for the feedback

Just to be on the same page which listeners are fired after `onSuccess`/`onFalure`?

Actually, `onFailure` can be called after `onSuccess` on token expiration. To prevent this call `token.markUsed` more details: https://github.com/hCaptcha/hcaptcha-android-sdk#good-to-know

**Comment by amusejfo** [comment]
@CAMOBAP No, it is just general reference clearing I am after. Since you are with each call to addOnSuccessListener/addOnFailureListener/addOnOpenListener adding to 3 different Lists there is the issue that there might either be dangling references that never gets cleared from those Lists. I'm looking for removeSucessListener/removeFailureListener/removeOpenListener. This becomes especially true when you are wrapping your listener callback setup with kotlin coroutines flow, and the scope might get cancelled.

**Comment by DSergiu** [comment]
Thank you for the suggestions @amusejfo .

The requested methods were released with [version 3.6.0](https://github.com/hCaptcha/hcaptcha-android-sdk/releases/tag/3.6.0).

**Comment by amusejfo** [comment]
Thank you ⭐
